### ISSUE TITLE
Feeds failed to load

### ISSUE THREAD

**Issue by callmepeanut** [crazyhitty/Munch#1]
Nice UI!
But when I try to add feeds and refresh, it show "Feeds failed to load" toast after "not working" toast.
I test several feeds, same problem, for example: http://us2.campaign-archive1.com/feed?u=887caf4f48db76fd91e20a06d&id=4eb677ad19

**Comment by callmepeanut** [comment]
I look into the code and find:

```
            if (mSource.equals("all_sources")) {
                mFeedsPresenter.attemptFeedLoading();
            } else {
                Toast.makeText(getActivity(), "not working", Toast.LENGTH_SHORT).show();
                //fix it later
                mFeedsPresenter.attemptFeedLoading(mSource);
            }
```

I know why, you have not  implemented single source yet.

**Comment by crazyhitty** [comment]
This toast was unnecessary, I most probably forgot to remove this part while publishing. Regarding the feed, the parser I made with jsoup fails to recognize this as a valid url. The parser unfortunately doesn't support every rss feed url yet. You can take a look at the library I created that parses the rss feed urls [here](https://github.com/crazyhitty/Rss-Manager).

The library is still in a very early stage, and I will try my best to fix it as soon as possible.

**Comment by crazyhitty** [comment]
Now users won't receive the toast message "not working". It was a mistake on my end. You will still get an error showing "Feeds failed to load" as I have not fixed the problem in the library yet.

**Comment by callmepeanut** [comment]
Oh, I tried http://www.engadget.com/rss.xml, it works.
