### ISSUE TITLE
Download entry contents for offline use

### ISSUE THREAD

**Issue by sarimak** [crazyhitty/Munch#10]
Maybe I have overlooked a configuration option but the feeds are scanned only for entry names - without downloading the contents. This may be fine for always-online 3G devices but is not useful for WiFi-only devices which are often used offline (subway, train). Could you please add such option to the feed management?
Flym has an option to read the contents upon synchronization.
Munch 0.42 from F-Droid

**Comment by crazyhitty** [comment]
You can sync the feeds from the context menu and it will save all of the feeds with their respective articles offline.
