### ISSUE TITLE
feeds showing no date

### ISSUE THREAD

**Issue by paulle** [crazyhitty/Munch#11]
Feeds show no date (no date available), I tried the same feed with another rss-reader and there was a date.
![screenshot_2016-03-12-16-48-10](https://cloud.githubusercontent.com/assets/4852079/13723914/db0facb6-e873-11e5-8923-52ae878229e1.png)

**Comment by crazyhitty** [comment]
Can you share the feed link please ?

**Comment by paulle** [comment]
I deleted the feed link, but with this one is happening the same.
http://rss.golem.de/rss.php?feed=RSS1.0

Am 12. März 2016 17:24:53 MEZ, schrieb Kartik Sharma notifications@github.com:

> Can you share the feed link please ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crazyhitty/Munch/issues/11#issuecomment-195769233

## 

K-9 Mail

**Comment by paulle** [comment]
This also happens with your preinstalled links. See screenshot.

Am 12. März 2016 17:24:53 MEZ, schrieb Kartik Sharma notifications@github.com:

> Can you share the feed link please ?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/crazyhitty/Munch/issues/11#issuecomment-195769233

## 

K-9 Mail

**Comment by crazyhitty** [comment]
Fixed in the latest build.
