### ISSUE TITLE
Unable to load RSS feeds

### ISSUE THREAD

**Issue by walrus543** [crazyhitty/Munch#4]
Hi,
I use Munch v0.42 from F-Droid on a Nexus 5 - Android 6.0.1 (Storage permission has to be set manually BTW).
I can't load my RSS feeds.
1 example: http://www.numerama.com/feed/

I have attached a log.
Thank you.
[logcat_and_device_info.zip](https://github.com/crazyhitty/Munch/files/165121/logcat_and_device_info.zip)

**Comment by coopy25** [comment]
also not working:
https://www.gamingonlinux.com/article_rss.php

**Comment by paulle** [comment]
Cannot load rrs-feeds too. Using cm12.1 and recent Munch from f-droid.

**Comment by ghost** [comment]
Same thing on the Nexus 5X. Feeds from the app's curated list load, but those added from a feed URL won't.

**Comment by crazyhitty** [comment]
Fixed in the latest build.
