### ISSUE TITLE
Unable to parse the feed

### ISSUE THREAD

**Issue by sarimak** [crazyhitty/Munch#5]
Unable to parse the feed: http://blog.tomashajzler.com/feed at all
Flym/SparseRSS can parse it without issues.
Munch 0.42 from F-Droid

**Comment by hajowieland** [comment]
Ich have this issue with nearly every Second feed From my Imported opml file exported by feedly :(

 was hoping so intense that this would finally replace feedly and manage all sync locally without a Server..

**Comment by ghost** [comment]
Error message is:

```
org.jsoup.UnsupportedMimeTypeException: Unhandled content type. Must be text/*, application/xml, or application/xhtml+xml. Mimetype=application/rss+xml; charset=UTF-8, URL=http://blog.tomashajzler.com/feed
```

**Comment by crazyhitty** [comment]
Fixed in the latest build.
